version: 2

jobs:
  build:
    parallelism: 3
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.6.1-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
      - image: circleci/postgres:9.5-alpine
    steps:
      - checkout

      - run:
          name: Install cmake
          command: sudo apt-get -y install cmake

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - ama-bundle-v2-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: ama-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - ama-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn Install
          command: yarn install

      - save_cache:
          key: ama-yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run: bin/rails db:create
      - run: bin/rails db:schema:load --trace
      - run: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: test_results
