default: &default
  adapter:  postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password:

development:
  <<: *default
  database: ama_development

test:
  <<: *default
  database: ama_test

production:
  <<: *default
  database: ama_production
